# Etiske refleksjoner omkring å insentivere institusjoner og respondenter med Mesos-rapporter

Det er i blant nyttig å kunne motivere institusjoner og deres individer til deltakelse i spørreundersøkelser ved å tilby noe tilbake. Dette kan medføre noen etiske problemstillinger som vi diskuterer her, oppdelt i nivåer/områder.

1.  Rapporteringen i seg selv, uten at man har informert om den og derfor blir en slags overraskelse, kan være uetisk. Vi anser det som uheldig å droppe å informere skolen/lærerne på forhånd. Det kan tenkes at man ville svart litt annerledes dersom man var klar over at ens aggregerte svar ville frembringes til hele kollegiet og ledelsen – selv om vi vel skal prøve å unngå spørsmål som henger ut personer. Bryter man dette prinsippet (dvs. ikke informerer individene på forhånd) bør man i størst mulig grad være sikker på at antall svar ved hver institusjon er tilstrekkelig høyt til at en liten gruppes "ekstreme" svar verken vil påvirke det store bildet eller henge ut leder/andre individer, og at spørsmålene ikke er sensitive.

2.  Med utgangspunkt i punktet ovenfor er det derfor best å informere skolen og lærerne på forhånd. Man åpner da for at institusjonen/respondentene kan ytre seg om de ønsker ordningen, eller om den må tilpasses/fjernes for akkurat dem. Videre vil det å informere om at det kan komme en slik rapportering, uten å opplyse om hva grensen for rapporteringen er (f.eks. 8 svar), vil i seg selv skape noe press på respondentene. Er det for få svar vil institusjonen miste godet. Likevel, grensen er ukjent og dersom det også er ukjent hvem som er invitert, så vil man ikke med sikkerhet vite hvem om en selv er den ene som mangler for å oppnå godet. Et slikt press synes ikke å være betydelig verre enn presset man vil oppleve fra sine kolleger/medelever/peers om et viktig tema man kan uttale seg om.

3.  Neste nivå er om man opplyser den spesifikke grensen for mottatte svar for at man skal kunne tilby institusjonen en rapport (ev. annet frynsegode). Setter man et konkret minimum (f.eks. 8) vil potensielt den 8. læreren føle press på å gjennomføre for ikke å ødelegge for alle de andre. Presset kan være reelt ved at andre har opplyst om at de selv har svart, og har funnet ut av at den 8. personen også har mottatt invitasjon. Vet man også at institusjonen har nøyaktig 8 individer vil det medføre åpenbar press på nr 8. Når det senere viser seg at det ikke kommer noe rapport er det tydelig at enten har person nr 8 ikke gjort det likevel, eller så har en av de andre som påstod at de har gjort det løyet. Ser vi bort fra en ekstrem situasjon der man regelrett blir tvunget til å vise frem bevis på sine svar, så vil det altså være et middels høyt press på de potensielle respondentene. For man kan lyve at man har gjennomført, slik man kan for enhver spørreundersøkelse.

4.  Et siste nivå i etikken her er om 8 er nok, eller om kriteriet bør være høyere. Dette er et svært komplekst spørsmål om personvern og anonymisering som drøftes av flere. Se for eksempel <https://www.duo.uio.no/handle/10852/69142> og <https://sdcpractice.readthedocs.io/en/latest/SDC_intro.html>. Minimumskriteriet vil alltid avhenge av hvor mye man bryter ned fremvisningen (tabeller og figurer) på, samt sensitiviteten i spørsmålene.
